### ISSUE TITLE
statistics: nodeinfo discovery seems to generate wrong json

### ISSUE THREAD

**Issue by DeusFigendi** [redmatrix/hubzilla-addons#108]
I'm just playing around a little with nodeinfo and I found several hubzilla nodes generating an invalid `.well-known/nodeinfo`

For example https://hub.kosmospora.de/.well-known/nodeinfo or https://hubzilla.top/.well-known/nodeinfo

both running pretty modern versions of hubzilla I think but the meta element is not as described in https://github.com/jhass/nodeinfo/blob/master/PROTOCOL.md

The json should contain an object (or dictionary) with `links` as a key and `links` should be an array (or list) of objects containing `rel` and `href`
but instead on kosmospora it generates an object with the keys `0` and `links` and both contain an object not an array.
And on hubzilla.top it also genrates a field called `links` (that is correct) but it doesn't contain an array but again an object.

Well [/statistics/statistics.php](https://github.com/redmatrix/hubzilla-addons/blob/master/statistics/statistics.php#L26) seems to generate it correct as for my eyes, I'm just not sure.

**Maybe** those pods just didn't update their addons since their software is up to date but I cannot verify this.

Mentioning @zotlabs and @annando as authors of the plugin

**Comment by zotlabs** [comment]
We no longer generate statistics.json and the nodeinfo issue was sorted several months ago.

**Comment by DeusFigendi** [comment]
> We no longer generate statistics.json

Nah, *statistics* is just the name of the addon I am reffering to :-)

> and the nodeinfo issue was sorted several months ago.

Ah this must be 7c59d29e7d023369fde807a71f631866ae143c8a so this is probabbly an invalid issue, sorry for bothering.

What a pity (and a shame) so much stuff in the fediverse doesn't get its updates :-/

**Comment by zotlabs** [comment]
Srry - was looking at the wrong line number. 

It took a while (over a year) to discover that the-federation.info wasn't reading our nodeinfo and falling back to statistics.json. While investigating that I uncovered a number of issues - some were ours like this one, and some "undocumented requirements" and then some undocumented behaviour on the part of the-federation.info (which is why nodeinfo 2 comes before nodeinfo 1). This coupled with the fact that this project and its wide array of configurations don't fit into any of the neat little categories that nodeinfo insists everything fit into. Anyway, we should be basically compliant now, but it's a wretched spec and most of this stuff was shoved down our throat. You technically can't have two way federation with Wordpress, yet we do; and for the first year we were forced to call our software 'redmatrix', even though that project was already dead when the spec was written.  Little stuff like that.
