### ISSUE TITLE
Bookmarker broken

### ISSUE THREAD

**Issue by rmonret** [redmatrix/hubzilla-addons#15]
Bookmarker does not work on my Hubzilla 1.2 installation. It did not work before either (Hubzilla 1.0 and1.1). Blablanet reported issues with bookmarker on his sites as well.

**Comment by jeroenpraat** [comment]
Please describe in detail what exactly the issue with the bookmarker you are having. For me it works. It displays the bookmark icon and you can click on it to bookmark an item.

**Comment by redmatrix** [comment]
Also works fine for me.

**Comment by jeroenpraat** [comment]
I have this issue now too, but only on my default (jeroenpraat) channel. 
I tried to re-enable the plugin, but without success.

**Comment by jeroenpraat** [comment]
Oh wait, it's only a problem in from Redbasic derived themes. Let me investigate this.

**Comment by jeroenpraat** [comment]
OK, I see it. It is this:
```
if(! function_exists('redbasic_init'))
		return;
```

Is this really needed @redmatrix ?

**Comment by redmatrix** [comment]
This is there because we're providing an icon font character and different themes may not use the same font icons. Thomas's themes for instance did not use font-awesome at all. On derived themes it is optional to go with the parent font icons or to roll your own. This was the best way at the time of ensuring that the bookmark font icon was actually available given all the different theme possibilities.  If you would like to improve on this, feel free to do so. You could perhaps replace it with a .png but that will present a different set of issues as you would then need to be aware of the text/background colours and ensure the .png is visible in all cases.

**Comment by jeroenpraat** [comment]
OK clear. But what is wrong with removing these lines and write in the plugin notes that font-awesome is required? Anyhow, I'm going to take a look later today. Maybe we also have to hide the #^ in UNO hubs, but that probably needs to be put in core.

**Comment by jeroenpraat** [comment]
Hooray! I fixed it. :-)

> Replace #^ with a bookmark icon. Font awesome is used for Redbasic and derived themes. A neutral dark grey PNG file is used for other themes.
