### ISSUE TITLE
ldapauth: Login only with LDAP password

### ISSUE THREAD

**Issue by arunisaac** [redmatrix/hubzilla-addons#29]
I set up the ldapauth plugin. Now, I am able to login with both my LDAP password and my account's hubzilla password. Is this expected behaviour?

I would like to be able to login only with my LDAP password. Is this possible?

**Comment by zotlabs** [comment]
In fact it has been some time since there has been any development with this addon; but if I recall correctly, it is designed or can be configured to auto-provision an account. If your first login is via LDAP, an account is created but with no local password and LDAP is the only authentication method which will work on that account unless you set the local password in the account settings. I'm not certain there is a setting currently to disable setting an account password, but that is relatively trivial to accomplish.

**Comment by arunisaac** [comment]
I have an account that I have already created with an account password. It now works with both the account password and the LDAP password. Can I somehow disable that account's password so that it works only with the LDAP password?

**Comment by zotlabs** [comment]
Set account.account_password to an empty string in the DB. Unfortunately this can't be done on the account settings page because we don't allow you to enter an empty password there; as an empty password cannot be used to login.

**Comment by arunisaac** [comment]
Yes, that works. Thank you!
