### ISSUE TITLE
Upcoming protocol changes in Diaspora

### ISSUE THREAD

**Issue by annando** [redmatrix/hubzilla-addons#46]
On the 33C3 @SuperTux88 and me discussed about future changes to the Diaspora protocol to support events and multiple threaded posts.

Although Diaspora can't work with it at the moment we will start in Friendica to transmit this data. See this function: https://github.com/friendica/friendica/blob/4053499c38cc4191fd4bf4724d17c968ecd2f756/include/diaspora.php#L2951

Additionally we can attend an event as well: https://github.com/friendica/friendica/blob/4053499c38cc4191fd4bf4724d17c968ecd2f756/include/diaspora.php#L3175

Additionally we now transmit a new field to allow multiple threaded comments: https://github.com/friendica/friendica/blob/4053499c38cc4191fd4bf4724d17c968ecd2f756/include/diaspora.php#L3245

Additionally the date format is now standardized to ````Y-m-d\TH:i:s\Z```` (Which is ISO 8601 with an added "Z" for telling that it is UTC). The old format is still accepted but please use this one in the future to avoid problems with upcoming changes.

The Diaspora documentation under http://diaspora.github.io/diaspora_federation/index.html will be updated soon to reflect these changes.

These new changes affects the way the signing is done and will break communication with systems that uses a static field order to check the signature. In short, this doesn't work anymore: https://github.com/redmatrix/hubzilla-addons/blob/master/diaspora/inbound.php#L1001 - Please have a look at Friendica to see how it has to be done now: https://github.com/friendica/friendica/blob/develop/include/diaspora.php#L415 (look at the variable $signed_data)

It is now possible to transmit additional fields in the comments and they will be relayed to other systems - even if Diaspora itself can't handle these fields. Please be in touch with @SuperTux88 concerning the naming if you want to add new fields.

Please be aware that future releases of Diaspora will switch to new field names (have a look at the linked documentation) which will break communication with systems that haven't adopt these changes. These changes are a part of the way to make the Diaspora protocol more flexible and open to other systems.

**Comment by zotlabs** [comment]
Could you possibly provide a quick XML snippet of what this looks like in a D* message? I can track through your code easily enough, but it's unlikely I will be doing this work - so an example of the output we're trying to produce would be most helpful.

**Comment by zotlabs** [comment]
In order to adequately express Friendica and Hubzilla events we probably also need an (optional) end or finish time and an indication of whether the event is local or global (this affects whether it should be converted to the local timezone or left as absolute UTC).  Detailed description and location would be nice, as well as repeat; but finish and 'adjust timezone' are what I would consider basic essentials. 

One *could* also provide the entire event as a vcalendar entry which has the advantage of already being well defined, although this can get rather complicated when dealing with 'attending' messages due to the different network namespaces involved (not to mention Hubzilla's nomadic identity). Still it may be worthy of consideration because it's so prevalent and convertible to a range of calendaring systems. One does not have to implement the entire ical suite; as most ical providers just store the entire received entry as a text blob and then just extract or generate/update the handful of fields they know how to deal with.  [Just mentioning this in case it triggers lightbulbs - we've been converting events into text and sending as Diaspora posts for several years, so anything which is somewhat structured and more easily parseable is an improvement].

**Comment by SuperTux88** [comment]
Did you even read the content of my linked PR? Also I think that it's better to discuss event-specific stuff there (because this issue is about multiple things hubzilla specific)

But a short answer:
* (optional) end or finish time ✔
* indication of whether the event is local or global ✔
* Detailed description ✔
* location ✔
* repeat ✘ (If we have multiple repeated events with the same GUID it isn't possible to attend to only one of them, so I think it is better to generate multiple unique events with it's own GUID. But as mentioned, we can discuss details about the protocol format in the linked PR)

**Comment by zotlabs** [comment]
Sorry I went page down from properties and ended up on participations and completely missed the optional properties in between. 

Repeat is definitely messy. No worries.

**Comment by SuperTux88** [comment]
> Sorry I went page down from properties and ended up on participations and completely missed the optional properties in between.

Oh, that makes sense now, no worries.

> Repeat is definitely messy. No worries.

So I think we should federate repeat with multiple single events.

**Comment by zotlabs** [comment]
We'll be mapping from iCal so my best thought atm is to use guid+recurrence-id as the 'federation guid'.

**Comment by zotlabs** [comment]
> What is the exact use case for a global one?

New Years is at midnight January 1, no matter where you are in the world. 

The Sydney Harbour fireworks start at 23:45 Australian Eastern Time.  If you want to see them live you need to convert to your local time. 

As for your example, a local event is always stored in UTC, and by default we enter them in our local time and display them in the viewer's local time. Then it is correct for viewers in any timezone.  It's easy enough to provide event timezone selectors on the event creation form and/or the events (display) page if you desire them.

**Comment by annando** [comment]
Concerning "new year" I think it would be better to use some "all day" flag with a date but without a time for that. Is there any use case for an global event with a time value?

**Comment by zotlabs** [comment]
"We wish to observe a moment of silence at the 11th hour of the 11th day of the 11th month to honour the fallen soldiers".

**Comment by annando** [comment]
Is this some fabricated example? I - personally - couldn't think of any real example.

**Comment by zotlabs** [comment]
No, in Australia we always observe a moment of silence on November 11th at 11AM (when the Armistice went into effect for the Great War (WWI). I presume they do so in many places in Europe as well; although they may have given up this practice after WWII. I also recall on 'Earth Day' we were asked to turn out all our electric devices for an hour starting at 6PM (18:00) if I recall. This was a global event. It isn't common but it does happen.

**Comment by annando** [comment]
I never heard of this - maybe because my country wasn't on the side of the world during the world wars :-)

I think @SuperTux88 should decide what to do with this.

**Comment by zotlabs** [comment]
When I created that setting in Friendica I called it 'adjust' to reflect it's true usage - whether or not to adjust the event for local time. iCal does something similar but uses a different mechanism. Both allow you to use any start time. 

Note that Hubzilla events are partially migrated to iCal and we should be completely migrated in the first half of 2017. So there are going to be a number of Hubzilla events which probably won't federate using this protocol modification. For instance we have task/to-do-list sharing with Outlook and Thunderbird today and the proposed protocol schema won't handle these event structures at all.  So this change is mostly for Friendica's benefit. It will have only a minimal effect on Hubzilla federation.

**Comment by annando** [comment]
So the question is what should be added to the protocol so that Hubzilla events can be transmitted with it.

**Comment by zotlabs** [comment]
All we need is a text blob that will hold the vcalendar entry.

**Comment by annando** [comment]
I don't really like the idea of some blob entry since they could be used for passing **anything** to another system, even large binary data. I suggest to use separate XML elements that are inspired by the corresponding RFCs.

**Comment by zotlabs** [comment]
There are hundreds of X-SOMETHING options used by various vendors. If you want to federate two calendar systems you must preserve these vendor extensions in your app and use/update the fields which interest your app. If you are worried about binary data, you can always sanitise it. With a text blob I can sync a calendar from Thunderbird, send it to my friends on Hubzilla (Diaspora, Friendica, wherever), and they can sync this to their Outlook. If one of them then sends me the same event using email from their Outlook, Thunderbird will recognise the duplicate and ignore it (or sync it if there are attendance updates). With defined separate elements this won't really work unless you support the entire iCal suite and all known extensions, and all of our projects combined don't have enough developers to maintain just this component.

**Comment by zotlabs** [comment]
I see from the related Diaspora issue that supporting ical directly isn't favoured by any of the critical people who would need to sign off on it, and I think you're probably stuck with the limited federation model of a few key fields. So just do whatever works for Friendica and Diaspora. 

Some day when you have time, I recommend reading this:

http://sabre.io/dav/building-a-caldav-client/

**Comment by CSammy** [comment]
> I see from the related Diaspora issue that supporting ical directly isn't favoured by any of the critical people who would need to sign off on it

It is not useful to support all iCal fields directly in the federation as this is, as you pointed out already, a huge standard which would be difficult to maintain. Inserting a blob is not in the spirit of the federation, which aims to transfer defined structured data between parties.

> and I think you're probably stuck with the limited federation model of a few key fields.

The federation model is not limited to a few key fields. It actually only _requires_ a few key fields. Additional fields are to ignore if they cannot be used by the receiving endpoint. We will not only do what works for Friendica and diaspora\*, but also for the entire federation. We support the federation. I personally would prefer if you refrain from guessing instead of checking facts.

Allow me to use your own words.

> Some day when you have time, I recommend reading this:

https://diaspora.github.io/diaspora_federation/entities/post.html (and related pages)

> In a nutshell, it's probably wrong to think of an event as a series of defined fields. Think of it more as a git repository which applications check fields in and out of.

I don't see any connection to the federation model. It is about communication between endpoints in a standardized manner, not about implementing logic and/or supporting other formats. Assuming a connection between a git-like data model and the federation would be possible is a strong hint for a misunderstanding what the federation is about.

In my opinion, the best way to work with repeated events is to perform the logic in one endpoint, and use the federation to transfer the events to other endpoints. This means, your endpoint creates the events belonging to the series, and sends them one by one to the relevant remote endpoints. You can mark all of the events as belonging to one series, but transfer each event on its own. I doubt this will ever be a bottleneck, and if it becomes one, we are still able to rethink our approach of federating events.

**Comment by zotlabs** [comment]
iCal is a federated event standard with years of experience and hundreds if not thousands of inter-operable implementations which have all figured out how to work together. To a large degree they have all altered the way they work internally in order to achieve a high degree of federation w/r/t calendering and event data. 

Other projects are free to either embrace or dismiss this tested and widely deployed model of federation.  As a project, we at Hubzilla have chosen to embrace it.  Note that we began several years ago by federating discrete and well-defined fields. Then the required fields began to grow. Then people wanted task lists and the ability to sync with or import/export to other calendaring systems.  So it's not like we're going into this blind and with no relevant experience. Our needs have grown and iCal is the only workable solution for those needs. We know the alternatives and they will simply not work and will not federate in the ways we desire. 

In any event whatever Diaspora as a project decides to do internally has no relevance to Hubzilla. 

If there are relevant plugin issues affecting the Diaspora protocol plugin please file them against the diaspora component of hubzilla-addons.  There is no core Hubzilla functionality involved. The mentioned signing format issue is invalid as the line referenced is no longer used and remains primarily for historical reference. (Admittedly it should probably be commented out.)

**Comment by annando** [comment]
This issue wasn't only about the events but also about allowing multi threaded comments, see the parameter ````thread_parent_guid````in the documentation at https://diaspora.github.io/diaspora_federation/entities/comment.html

Friendica does support this parameter and Diaspora is relaying this as well. Since Hubzilla does support multi threading as well, it would be great if this parameter could be supported as well.
