### ISSUE TITLE
Diaspora: Received strange mixture of comment and like

### ISSUE THREAD

**Issue by annando** [redmatrix/hubzilla-addons#47]
Recently my Friendica server received this message:

(The values are anonymized)
````
<XML>
  <post>
  <comment>
<positive>true</positive>
<guid>someguid@hubzilla-server.tld</guid>
<target_type>Post</target_type>
<parent_guid>comment-guid</parent_guid>
<diaspora_handle>user@hubzilla-server.tld</diaspora_handle>
<author_signature>some-author-signature</author_signature>
    </comment>
  </post>
</XML> 
````

That server is running version 1.14.3.

There are multiple problems with this message. It has the content of a "like" message but is wrapped inside a comment message. Additionally the parent_guid points to a comment - but the "target_type" is "Post" (instead of "Comment".

Solution is to wrap the "like" content in a "like" message and to change the "target_type" to "Comment" when a comment is liked. Friendica does support this (and it is in the official Diaspora protocol documentation).

P.S.: An "dislike" is supported by the protocol as well. Then "positive" has to have the value "false".

**Comment by zotlabs** [comment]
It was probably a like of a photo or profile and we didn't have a code path specifically designed to translate this type of activity to Diaspora (since they don't really support activities) so it ended up using the wrong template.  Nothing more. I didn't bother to try and track this down because all the identifying information was stripped so there was nothing to track down and no actual activity that I could analyse. In the future, please try and provide some information we can use to positively identify the issue rather than just make guesses based on anonymised/fake data.
