### ISSUE TITLE
Diaspora: Breaking changes, starting in a few weeks

### ISSUE THREAD

**Issue by annando** [redmatrix/hubzilla-addons#49]
Nearly one year ago the plan was made to clean up the Diaspora protocol, see this issue: https://github.com/diaspora/diaspora_federation/issues/29

Over the time the changes were protocoled here: https://diaspora.github.io/diaspora_federation/index.html

The transformation to the new format is planned in three steps:

* Step 1: The system can receive the new and the old format but will send the old format. (this is valid for all recent stable Diaspora versions and for Friendica in version 3.5.0 and the upcoming 3.5.1)
* Step 2: The system can receive the new and the old format but will send the new format. (This will be done in a few weeks for the development version of Diaspora and I guess we will enable this in the Friendica version 3.5.2)
* Step 3: The system can receive and send only the new format.

How is Hubzilla prepared to this? For a given time it has to be able to understand both the old and the new format - or communication will break.

**Comment by git-marijus** [comment]
I think we should be fine for basic communication. We still need to update some templates to reflect the changed field names. The signing of messages in the new format should be fine though...

**Comment by annando** [comment]
To be able to communicate when in "Step 1", a system has to receive messages as well in the new but also in the old format since the systems will upgrade over a longer period.

**Comment by zotlabs** [comment]
We're in much better shape than you suggest from your 2 second code review of a plugin in a project that you don't care enough about to even try and understand at a technical level. 

Sending in the new format isn't yet implemented, and we don't yet implement a few of the new post "object" modes on the receive side. Since they are totally incompatible with our data structures, that's to be expected. We map those we can.

Anyway, I don't personally care whether it works or not and Diaspora compatibility is not a priority for Hubzilla as a project. Diaspora is fundamentally incompatible with Zot. However, it is implemented in an unsupported addon and Hubzilla works just fine without it.  As far as I know there are only 4-5 people who actually use the plugin and I don't know of any who care enough to actually do anything about it if it stops working.  I have no way personally to test the Diaspora protocol, so I will leave this and any other legacy protocol addons for people who care about it and decide to put some skin in the game.

**Comment by annando** [comment]
Since this addon is used for the communication between Friendica and Hubzilla as well, I'm interested in keeping this addon in a working state. However, I don't have the time to actively contribute to this project.

I'm closely cooperating with the Diaspora developers. So I am informed very well upon upcoming changes. I see it as my task to inform others about important changes so that there is enough time for them to apply to them. I wouldn't like the situation when something hadn't be done just because of missing information.

**Comment by annando** [comment]
A reminder: the changes will be applied in some weeks: https://github.com/diaspora/diaspora/pull/7436#issuecomment-299732311

The changes will also include changes to the salmon handling that Friendica had done here: https://github.com/friendica/friendica/pull/3443

**Comment by zotlabs** [comment]
At this point in time, Hubzilla is prepared to accept Diaspora salmons and the "new protocol". But there is only so much preparation we can do without valid examples of this protocol in the wild. Diaspora has traditionally double-encoded things and used different hash algorithms than what is described in their "specifications"; which I've therefore treated as fictional documents. Also the "new salmon" is not valid against any revision of the salmon spec or drafts that ever existed. So all we can do is try to anticipate the worst case and prepare some fallback mechanisms for the most probable ways they could screw up their own implementation based on historical context; and hope that this time the specs _vaguely_ resemble reality - at least to a point where we can get them working once these packets actually appear in the wild. 

If you have broken communications and logs of the new protocol against Hubzilla servers (at least the small minority of Hubzilla servers that enable the Diaspora protocol addon) please provide such logs and examples of the messages involved so that they can be examined and those particular failures analysed. If possible against a 2.4RC or later server since there were some minor compatibility fixes to the Diaspora protocol since 2.2 was released back in February or March; but if that's all you have to work with, it's better than nothing - which is what you've provided so far. Just be prepared for somebody here to knock some issues back with "already fixed".

Nobody is asking for you to contribute to this project. We only ask that people provide clear bug reports.
I find the lack thereof and the general ignorance of the huge amount of work that **has** been done to prepare for this protocol change quite disappointing. Not surprising unfortunately, but disappointing.

**Comment by annando** [comment]
AFAIK the documentation of the Diaspora protocol at https://diaspora.github.io/diaspora_federation/index.html describes the new protocol very accurate. Some days ago I was able to perform tests against a Diaspora server that had the new format enabled. The server send the messages like described in that document.

Additionally you can have a look at the Salmon implementation at https://github.com/friendica/friendica/blob/develop/include/diaspora.php#L190-L261 and https://github.com/friendica/friendica/blob/develop/mod/receive.php#L41-L54 

Currently Friendica is planning to release the 3.5.2 soon, we had already created a RC branch. One of my first tasks for the 3.5.3-dev (that is expected for somewhere in June) will be the transmission of the new format. Then you can do some "real life" tests with the new protocol.
