### ISSUE TITLE
Hubzilla events do not federate to Diaspora

### ISSUE THREAD

**Issue by git-marijus** [redmatrix/hubzilla-addons#6]
Works in r#
I don't think this has to do with my recent changes... Just discovered because i wanted to do some testing...

**Comment by royalterra** [comment]
Yes is true me to with the seam issue

**Comment by zotlabs** [comment]
Did not respond to this earlier because it worked for me. It still works for me. The format is somewhat ugly because we aren't calling format_event_diaspora(); but I see no issues with basic communications.

**Comment by zotlabs** [comment]
Just saw a Friendica discussion which mentions events failing to federate which contain the bbcode map tag. This may be an important clue which may be at play here due to the "peculiar" way we render these during the bbcode->html->markdown conversion. Friendica's map tag rendering is essentially a copy of hubzillas.

**Comment by royalterra** [comment]
Uhm Possible for some people still work some add-ons and for others  not because Update Addons not see to works in the admin GUI . Is a issue I comment with other developers because produce other nasty issues like duplicated icons  I look around the code but I will look again now in my holidays soon or late many people will have a broken hub because addon is not update with hubzilla.  
In Friendica there also a fix days ago about "Adopt limitation of usage of "-" in username to avoid conflicts with GNU Social and Diaspora " what can be and other clue.

**Comment by zotlabs** [comment]
> people will have a broken hub because addon is not update with hubzilla

util/udall
