### ISSUE TITLE
how to install phpmailer

### ISSUE THREAD

**Issue by slobinger** [redmatrix/hubzilla-addons#65]
Would like to use phpmailer. But if I try to install it via Web-UI I get
```
2017-10-02 17:54:08:LOG_INFO:lnpm55kt49f3lvi7n0fkdp0c61:plugin.php:108:load_plugin: Addons: FAILED loading phpmailer
```
in app log.
using the current hubzilla code on master branch. Any idea what am I doing wrong or how I can try to fix this?

**Comment by zotlabs** [comment]
Despite the unfortunate log message, it actually works. The plugin was using an older install/uninstall method rather than the newer load/unload functions. The plugin still works but generates a log message because the load function wasn't found. This has now been fixed upstream but you can still use the plugin before this gets merged into the main code.

**Comment by slobinger** [comment]
OK phpmailer works. Solved the encoding issue by adding
```
$mail -> charSet = "UTF-8";
```
to my  phpmailer.php
