### ISSUE TITLE
Diaspora: Comments are partly containing "diaspora_handle" instead of "author"

### ISSUE THREAD

**Issue by annando** [redmatrix/hubzilla-addons#69]
I got relayed this post from a Hubzilla-Server:

`<?xml version="1.0" encoding="UTF-8"?>
<comment><guid>42244ac09e3501355536543d7ed6cc36</guid><parent_guid>cabc37074e91a1e7f0d417f79459c372f7687cec976d83c7a7ca335a3e43765f@hubzilla.online</parent_guid><text>dein experiment diapsora srever ist ja verunglückt ...</text><diaspora_handle>plage@diasp.de</diaspora_handle><author_signature>b62QWZjQALpQLj547ssMaptA0et0QGw9coWBM4qOneXPgAU4gDOGb72gKdipikxvkQLXHcHIhkwqQhEEsSr00i8ViYzg3mOYSnB3b+GsfvGFyxoQ8ql3V1hXB6QRJVvCDPr7J13Dll6irOzNo/zvrt28noelGRxoxKmA/9Si85JcVGbk86goXKtBx94IlreL7OOpQG1S44HTXMAiaWyrdD77VrSq1on2bjwo6fJvjAen7vlDk/kNSLZF1dkP9KPi8N7DmkRCofah5eMU0M0JSFk2ynwhgtKjExypyfqoUSBIx8BD5ueBC4Va6hUYDZLE81XFghrt/0u0un4K3JDh4wunGFx8BUSLA8WP8kNyHNG4RmWxH5azl8mKP9b3UI8O7CQrl87qRKzoLTdOR4ewlpuJBulWc8bWmecbrX7mTwVq0bS/F35AdURLwpoXovUoE1f0enP8Aw2lOEAl4usAdWE1bYyfJ/nfL6uYE5hCiU3nuHAUbdM6eavb9snfFmZEpv3CMXSYLImGFnYVFGWZLVyhb5KqcvfAlvRKY95ysnW3H/0A3og0HPRevNu/7JFVEa8uXZOawZRTECXW5nu4zUDawWEFLKQGUSpZYAkAjhCQkmyin639GtGrNSIdMDi2GOfmYLa/TAd4VUpWq+kWUlynSsqFhX3OX7Nmj6rInhc=</author_signature><parent_author_signature>xELUNScX+7bplbrXiKDlhEgnGz6duj20Ohuarg4EBAgInyLXsCto7ZReC1PYoX3qT16BC870qiwsWL5M6fO/8A1HdcZavzifcAlt/rgU9sp0nY8953bMtI4XBjXf8Vnolp8p6+nWVeTyOO0aWHjCv2vB/16IxFzztmx30KA5XnpGnygLSyPPuM3sevAVXmxYkQK5cu/0NQ11KMz6m+wIlOgfT0q+DaBUchOhTcHkpVJabv0cr3qjI5UBs52D9zGfs3mQt6jlSFqID/LLj2vQKdJ0zSxQ5dtFYlxX9nTLyGoZY+eZYN5JR/6KI3ssotL1vXBLdMOtHgs4hkAONm0A5ZKLzaeVvdinb5ossIz4KYLvPH+Zu5BO0rPn43yEh9R0Srs6j9rcECKc5NFXS8fc3e/evYM63WdluNQeordQSQrMxaoHHsCoG6UsElrn8a7BRUOUrifiYrEaA5uADCYcaBDJ/Hs5DKuJbrJlzASX808iZXEMWnV/yCIvyRnT4Y+y+9/HNlRem2BFLNmzX5eBjFHKqWN1JD0FaHVpUHe9fq6r04n+dVMh+7siv6VGByOYC6e6VQQD1z8KLDHuc0Fc70UydzALbmEOq+Xx4NduruMYi9BciMIRN0Moppx+o1ImyCpdXQBjkYIpS3apmv7sac3oSK0kA8GUo8Kj/3tQrzM=</parent_author_signature></comment>`

Problem is that it is transmitted in the new format and so it had to use ```author``` and not ```diaspora_handle```.

**Comment by zotlabs** [comment]
Tough call because the signed fields were from a diaspora server running 0.6.7. If we change the field names to match the protocol version we send it invalidates the otherwise valid signature. I would call this a Friendica bug, but I'm willing to accept that I might be wrong. We accept the old protocol and send only the new. Comments and their associated fields are relayed as received because that's what was signed. You can ask the Diaspora folks but I believe we're doing this correctly and I believe Hubzilla would accept and validate this comment.

**Comment by SuperTux88** [comment]
The field name isn't part of the signature, so as long as the order stays the same, the signature is still valid. That's exactly what diaspora does, we receive an old message, but send it the new way, including new field names (it isn't stored with which field names it was received, because it isn't important).

However: Diaspora currently supports receiving new protocol with old field names, because we always convert the field names to the new names internally (and work always with new names), unrelated if it's received with old or new protocol.

But it's hard to tell if this is a friendica bug or hubzilla bug, because it's an unspecified half new/half old format. But for me it makes more sense for hubzilla to always send the completely new format instead of friendica adding support for this half/half format (because as soon as diaspora removes backward-compatibility we wouldn't accept this half/half format anymore, while we still would receive the completely new format).

**Comment by zotlabs** [comment]
I forgot that people exist who cling stubbornly to dead protocols. 

Long story short: fixed in red. Whether or not the fix ends up in hubzilla is up to the hubzilla community.
